### ISSUE TITLE
How to build a web page like this?

### ISSUE THREAD

**Issue by YangLaTeX** [pgf-tikz/pgf-tikz.github.io#1]
Two main questions
1. how to build the style of this web page
2. how to convert such big amount pdf pages to independent svg files

Many thanks!!

**Comment by hmenke** [comment]
This is not really a web page, but just the SVG version of the PGF manual.  All the SVG-specific code is in this directory: https://github.com/pgf-tikz/pgf/tree/master/doc/generic/pgf/version-for-dvisvgm
The build script for the manual is in https://github.com/pgf-tikz/pgf/blob/master/build.lua and deployment to GitHub pages is done in https://github.com/pgf-tikz/pgf/blob/master/ci/update_website.sh
